# Site settings
title: WhatsGood 
logo: "/images/Crave-Logo-Color.png"
external_site: "http://whatsgood.services/"
email: sergio@cravefood.services
description: > # this means to ignore newlines until "baseurl:"
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://jobs.cravefood.services/" # the base hostname & protocol for your site
#twitter_username: jekyllrb
github_username:  CraveFood

# Build settings
markdown: kramdown
